In [11]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

# ___Classifier Decision Functions___
------------------

In [1]:
# Many classifiers in sklearn can provide information about the uncertainty associated with the predictions made by them.
# This can be accomplished by either the .decision_function() method or .predict_proba() method.

In [2]:
# Using the decision_function, given a set of test points, it can show how confidently the classifier predicts the positive class or the 
# negative class.

In [3]:
# predict_proba function provides the predicted probabilities of class membership.
# A classifier will typicaly predict the most probable class.
# e.g. in a binary classifier, the class with > 0.5 threshold.

# Adjusting this threshold affects the predictions of the classifier.
# e.g. only predict class A when the estimated probability of class A > 0.9

# Higher thresholds result in a more conservative classifier.
# This increases precision.

In [5]:
# This types of probabilities aren't always dependable since highly overfitted models may provide overly optimistic probabilities.

In [8]:
digits = load_digits()
train_x, test_x, train_y, test_y = train_test_split(digits.data, digits.target, train_size = 0.8)

In [25]:
# accuracy increases with generalization i.e C upto C = 1

svc = SVC(C = 0.015, kernel = "rbf", probability = True).fit(train_x, train_y)

In [26]:
svc.score(test_x, test_y)

0.46111111111111114

In [33]:
svc.predict_proba(test_x)

array([[0.54387965, 0.02127644, 0.01995575, ..., 0.03819977, 0.04836975,
        0.0742377 ],
       [0.62206514, 0.01266958, 0.02508093, ..., 0.02781751, 0.04184989,
        0.09935171],
       [0.05659976, 0.16163699, 0.01257843, ..., 0.04759629, 0.05325757,
        0.02818909],
       ...,
       [0.38737258, 0.04339229, 0.0188331 , ..., 0.03354512, 0.06356591,
        0.05517928],
       [0.02776121, 0.05368526, 0.2860604 , ..., 0.10689123, 0.11666122,
        0.10925754],
       [0.02022523, 0.08315526, 0.05104222, ..., 0.35596506, 0.11673192,
        0.0573882 ]])

In [29]:
svc.decision_function(test_x)

array([[ 9.28232575,  8.22668787,  0.7317436 , ...,  3.87917668,
        -0.273354  ,  1.82294624],
       [ 9.2872282 ,  8.19868528,  0.73945256, ...,  3.81649909,
        -0.27206493,  3.92834045],
       [ 4.9651618 ,  8.27094223,  0.72585085, ...,  3.87091924,
        -0.27652651,  1.76714624],
       ...,
       [ 8.27055173,  8.25447842,  0.72841971, ...,  3.81078711,
        -0.27104218,  1.7941288 ],
       [ 1.79093626,  9.2634777 ,  5.21347433, ...,  4.92717011,
        -0.26999281,  3.82902948],
       [ 2.76061707,  8.26528959,  0.7410199 , ...,  9.28699501,
        -0.25692851,  2.76446428]])

In [30]:
svc.classes_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])